### ISSUE TITLE
clone项目后下载完应用，运行的时候遇到的问题

### ISSUE THREAD

**Issue by parsebyte** [liguobao/Dy2018Crawler#2]
![default](https://cloud.githubusercontent.com/assets/12016007/20993485/86b3682e-bd25-11e6-8cb9-44636f2b914c.PNG)
新手请教一下

**Comment by parsebyte** [comment]
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head> 
<title>IIS 10.0 Detailed Error - 500.19 - Internal Server Error</title> 
<style type="text/css"> 
 
</style> 
 
</head> 
<body> 
<div id="content"> 
<div class="content-container"> 
  <h3>HTTP Error 500.19 - Internal Server Error</h3> 
  <h4>无法访问请求的页面，因为该页的相关配置数据无效。</h4> 
</div> 
 
<div class="content-container"> 
 <fieldset><h4>Detailed Error Information:</h4> 
  <div id="details-left"> 
   <table border="0" cellpadding="0" cellspacing="0"> 
    <tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;IIS Web Core</td></tr> 
    <tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;未知</td></tr> 
    <tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;尚未确定</td></tr> 
    <tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x80070003</td></tr> 
    <tr class="alt"><th>配置错误</th><td>&nbsp;&nbsp;&nbsp;无法读取配置文件
</td></tr> 
<tr><th>配置文件</th><td>&nbsp;&nbsp;&nbsp;\\?\C:\code\github\Dy2018Crawler\src\Dy2018Crawler\web.config</td></tr> 
   </table> 
  </div> 
  <div id="details-right"> 
   <table border="0" cellpadding="0" cellspacing="0"> 
    <tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;http://localhost:49539/</td></tr> 
    <tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;</td></tr> 
    <tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;尚未确定</td></tr> 
    <tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;尚未确定</td></tr> 
    <tr class="alt"><th>请求跟踪目录</th><td>&nbsp;&nbsp;&nbsp;C:\Users\LingFeng\Documents\IISExpress\TraceLogFiles\</td></tr> 
   </table> 
   <div class="clear"></div> 
  </div> 
 </fieldset> 
</div> 
  <div class="config_source content-container"> 
    <fieldset> 
    <h4>配置源:</h4> 
    <pre><code>   -1: 
<span class="highlight-code">    0: </span>
</code></pre> 
    </fieldset> 
  </div> 
 
<div class="content-container"> 
 <fieldset><h4>More Information:</h4> 
  当读取 Web 服务器或 Web 应用程序的配置文件出现问题时，就会发生此错误。在某些情况下，事件日志会包含有关导致此错误的原因的更多信息。<p></p><p></p>如果您看到文本“定义了重复的‘system.web.extensions/scripting/scriptResourceHandler’节”，则此错误是由于您正在 .NET Framework 4 中运行基于 .NET Framework 3.5 的应用程序导致的。如果正在运行 WebMatrix，则若要解决此问题，请转到“设置”节点以将 .NET Framework 版本设置为“.NET 2”。您也可以从 web.config 文件中删除多余的节。 
  <p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=500,19,0x80070003,9200">View more information &raquo;</a></p> 
   
 </fieldset> 
</div> 
</div> 
</body> 
</html>

**Comment by parsebyte** [comment]
\\?\C:\code\github\Dy2018Crawler\src\Dy2018Crawler\web.config

是配置文件需要修改路径？

**Comment by liguobao** [comment]
@parsebyte 
如果您看到文本“定义了重复的‘system.web.extensions/scripting/scriptResourceHandler’节”，则此错误是由于您正在 .NET Framework 4 中运行基于 .NET Framework 3.5 的应用程序导致的。如果正在运行 WebMatrix，则若要解决此问题，请转到“设置”节点以将 .NET Framework 版本设置为“.NET 2”。您也可以从 web.config 文件中删除多余的节。

你的VS版本和Core版本是？

**Comment by parsebyte** [comment]
@liguobao 2015 update3，Core是current版本的1.1

**Comment by liguobao** [comment]
@parsebyte 直接运行Dy2018Crawler.exe看看，我还没遇到过这样的错误。

**Comment by parsebyte** [comment]
@liguobao 
![default](https://cloud.githubusercontent.com/assets/12016007/20993791/8b428828-bd27-11e6-9f03-8ca31ffa5571.PNG)

**Comment by parsebyte** [comment]
@liguobao 有一个warning 
元素 “system.webServer” 的子元素 “aspNetCore” 无效。应为可能元素的列表: “asp, caching, cgi, defaultDocument, directoryBrowse, globalModules, handlers, httpCompression, webSocket, httpErrors, httpLogging, httpProtocol, httpRedirect, httpTracing, isapiFilters, modules, applicationInitialization, odbcLogging, security, serverRuntime, serverSideInclude, staticContent, tracing, urlCompression, validation, management, rewrite”。	Dy2018Crawler	H:\ASP-Work\Dy2018Crawler\src\Dy2018Crawler\web.config	12

**Comment by liguobao** [comment]
少一个nlog.config，我看看项目里面是不是没有这货了...

**Comment by parsebyte** [comment]
@liguobao 谢谢，麻烦大大了

**Comment by liguobao** [comment]
@parsebyte 
nlog.config在这里，有的。
https://github.com/liguobao/Dy2018Crawler/blob/master/src/Dy2018Crawler/nlog.config

在src/Dy2018Crawler 这个文件下运行一下下面的命令：
dotnet restore;
dotnet run;
理论上是直接能跑起来的...

 你装了core sdk和runtime么？
https://www.microsoft.com/net/download/core#/current/sdk
https://www.microsoft.com/net/download/core#/current/runtime

**Comment by parsebyte** [comment]
@liguobao 装了的= =，好像意识到问题了，我刚才直接点了VS里面的那个IIS Express....运行了

**Comment by liguobao** [comment]
@parsebyte 
Soga,切回到本地试试。

**Comment by parsebyte** [comment]
@liguobao 
![default](https://cloud.githubusercontent.com/assets/12016007/20994084/3b722ea0-bd29-11e6-956a-cd1497f49477.PNG)
是版本号没对齐导致的么？还是？

**Comment by liguobao** [comment]
@parsebyte 运行位置错了，是XXX/Dy2018Crawler/src/Dy2018Crawler 这个文件夹下面。

**Comment by parsebyte** [comment]
@liguobao 囧，感谢大大，我再试试

**Comment by parsebyte** [comment]
@liguobao success ! thanks !
