### ISSUE TITLE
请问mysql需要建立哪些表呢？

### ISSUE THREAD

**Issue by parsebyte** [liguobao/Dy2018Crawler#3]
看到大大最近加入了mysql，不知道要在数据库里建立那些表？

**Comment by liguobao** [comment]
@parsebyte 还没写好...Core上用EF有点坑。
用EF的话，不需要建表，直接用EF创建，等我下一个提交吧....

**Comment by parsebyte** [comment]
@liguobao 嗯

**Comment by liguobao** [comment]
https://github.com/liguobao/Dy2018Crawler/commit/7ff577656aaeb7385059d5a13babac9ef58b4a51

已经初步完成数据落地到MySQL数据库，数据库名为moviecrawler(你要改成别的也行)，不需要建表，EF会直接建表。
https://github.com/liguobao/Dy2018Crawler/commit/db97f51484c683d359dbea479fbc120cb015eca0

不过使用之前，请确保数据库连接字符串正确，数据库已存在，连接字符串在这个文件里面：
https://github.com/liguobao/Dy2018Crawler/blob/master/src/Dy2018CrawlerForDB/Data/DataContext.cs

暂时写死，懒得去读取配置了...^_^

还有确保MySQL版本在5.6 +(为嘛？因为用的MySQL EF驱动只支持5.6+)

ubuntu安装MySQL 5.7的方法如下：
$ sudo apt-get install software-properties-common
$ sudo add-apt-repository -y ppa:ondrej/mysql-5.7
$ sudo apt-get update
$ sudo apt-get install mysql-server

**Comment by liguobao** [comment]
@parsebyte 如上...
